### ISSUE TITLE
How to Use Etcd for Distributed KV Storage And Let the Dev choose Consistency/Speed

### ISSUE THREAD

**Issue by JackyChiu** [edegens/ptype#19]
Problem: We don't understand how to utilize etcd for our distributed key-value storage yet. 

Research and design how a system would work for this. Take into account our design for service discovery and find a way that compliments both. 

Examples of things we are unsure about:
- If we update a value on our local etcd, how does it get propagated to the rest of the nodes? Or do we always have to send writes to the leader?
- If we attempt to read a key on our local etcd and the value isn't there will it redirect it? Or do we have to request the leader for reads?

**Comment by JackyChiu** [comment]
I did some research into the etcd client to see how etcd might behave for the reads and writes. The client takes the configuration of multiple nodes in the cluster, this is most likely just the initial nodes in the cluster. 

The following link shows the different modes that can be used to determine which one of the nodes is selected for requests. These imply that the writes may go to any etcd node but will be routed to the leader, but doesn't clear up how reads behave. 

https://godoc.org/go.etcd.io/etcd/client#EndpointSelectionMode

**Comment by dipshit** [comment]
I have an initial PR that uses the etcd `clientv3.KV` interface as a guide for making a KV store [here](https://github.com/edegens/ptype/pull/34).

I want to continue working on using etcd itself as a KV store, instead of building our own. Our design doc didn't show any downsides to this, but many upsides (like less time).

**Comment by JackyChiu** [comment]
Curious what you guys think we should do about consistency, should we always read quorum or not or allow the user to provided the flag? The later sounds interesting to me

**Comment by JackyChiu** [comment]
Re: quorum reads/writes
https://github.com/etcd-io/etcd/issues/6829

**Comment by dipshit** [comment]
Thanks @JackyChiu 

For this issue to be closed I want:

1. The developer to be able to be able to specify params on `Get`, `Put`, and `Delete` (like `clientv3.WithSerializable()`)
1. Optional, but get rid of `GetPrefix` in favour of the above solution.

**Comment by dipshit** [comment]
`clientv3.OpOption` already has this functionality of variadic parameters. [docs](https://pkg.go.dev/go.etcd.io/etcd/clientv3?tab=doc#OpOption). I am going to build wrappers around these so that the developer doesn't need to import `clientv3` just to specify how our methods should behave. Building this wrapper will allow me to add a function like `WithContext()` in.

I like this solution as it is simple for the developer, and gives them the options of more configuration. We can also control the default `OpOption` when wrapping it.
